let num1= 9;
let num2=19;
console.log("addition:",num1+num2);
console.log("substraction:",num1-num2);
console.log("multiplication:",num1*num2);
console.log("division:",num1/num2);
console.log("remainder:",num1%num2);
console.log("exponent:",num1**num2);
console.log("squareroot:",(num1+num2)**(1/2));
console.log("squareroot:",Math.sqrt(num1+num2));
console.log("cuberoot:",Math.cbrt(num1+num2));
